; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --scrub-attributes
; RUN: opt -S -passes=argpromotion < %s | FileCheck -check-prefixes=ALL,NO-MSSA %s
; RUN: opt -S -passes=mssaargpromotion < %s | FileCheck -check-prefixes=ALL,MSSA --allow-unused-prefixes %s

define internal i32 @callee_basic(ptr %p) {
; NO-MSSA-LABEL: define {{[^@]+}}@callee_basic
; NO-MSSA-SAME: (i32 [[P_0_VAL:%.*]], i32 [[P_4_VAL:%.*]]) {
; NO-MSSA-NEXT:    [[Z:%.*]] = add i32 [[P_0_VAL]], [[P_4_VAL]]
; NO-MSSA-NEXT:    ret i32 [[Z]]
;
; MSSA-LABEL: define {{[^@]+}}@callee_basic
; MSSA-SAME: (ptr [[P:%.*]]) {
; MSSA-NEXT:    [[X:%.*]] = load i32, ptr [[P]], align 4
; MSSA-NEXT:    [[P1:%.*]] = getelementptr i8, ptr [[P]], i64 4
; MSSA-NEXT:    [[Y:%.*]] = load i32, ptr [[P1]], align 4
; MSSA-NEXT:    [[Z:%.*]] = add i32 [[X]], [[Y]]
; MSSA-NEXT:    ret i32 [[Z]]
;
  %x = load i32, ptr %p
  %p1 = getelementptr i8, ptr %p, i64 4
  %y = load i32, ptr %p1
  %z = add i32 %x, %y
  ret i32 %z
}

define void @caller_basic(ptr %p) {
; NO-MSSA-LABEL: define {{[^@]+}}@caller_basic
; NO-MSSA-SAME: (ptr [[P:%.*]]) {
; NO-MSSA-NEXT:    [[P_VAL:%.*]] = load i32, ptr [[P]], align 4
; NO-MSSA-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[P]], i64 4
; NO-MSSA-NEXT:    [[P_VAL1:%.*]] = load i32, ptr [[TMP1]], align 4
; NO-MSSA-NEXT:    [[TMP2:%.*]] = call i32 @callee_basic(i32 [[P_VAL]], i32 [[P_VAL1]])
; NO-MSSA-NEXT:    ret void
;
; MSSA-LABEL: define {{[^@]+}}@caller_basic
; MSSA-SAME: (ptr [[P:%.*]]) {
; MSSA-NEXT:    [[TMP1:%.*]] = call i32 @callee_basic(ptr [[P]])
; MSSA-NEXT:    ret void
;
  call i32 @callee_basic(ptr %p)
  ret void
}

define internal i32 @callee_basic_nogeps(ptr %p) {
; ALL-LABEL: define {{[^@]+}}@callee_basic_nogeps
; ALL-SAME: (i32 [[P_0_VAL:%.*]]) {
; ALL-NEXT:    [[Z:%.*]] = add i32 [[P_0_VAL]], [[P_0_VAL]]
; ALL-NEXT:    ret i32 [[Z]]
;
  %x = load i32, ptr %p
  %y = load i32, ptr %p
  %z = add i32 %x, %y
  ret i32 %z
}

define void @caller_basic_nogeps(ptr %p) {
; ALL-LABEL: define {{[^@]+}}@caller_basic_nogeps
; ALL-SAME: (ptr [[P:%.*]]) {
; ALL-NEXT:    [[P_VAL:%.*]] = load i32, ptr [[P]], align 4
; ALL-NEXT:    [[TMP1:%.*]] = call i32 @callee_basic_nogeps(i32 [[P_VAL]])
; ALL-NEXT:    ret void
;
  call i32 @callee_basic_nogeps(ptr %p)
  ret void
}

; Same offset is loaded with two differen types: Don't promote.
define internal i32 @callee_different_types(ptr %p) {
; ALL-LABEL: define {{[^@]+}}@callee_different_types
; ALL-SAME: (ptr [[P:%.*]]) {
; ALL-NEXT:    [[X:%.*]] = load i32, ptr [[P]], align 4
; ALL-NEXT:    [[Y_F:%.*]] = load float, ptr [[P]], align 4
; ALL-NEXT:    [[Y:%.*]] = fptoui float [[Y_F]] to i32
; ALL-NEXT:    [[Z:%.*]] = add i32 [[X]], [[Y]]
; ALL-NEXT:    ret i32 [[Z]]
;
  %x = load i32, ptr %p
  %y.f = load float, ptr %p
  %y = fptoui float %y.f to i32
  %z = add i32 %x, %y
  ret i32 %z
}

define void @caller_different_types(ptr %p) {
; ALL-LABEL: define {{[^@]+}}@caller_different_types
; ALL-SAME: (ptr [[P:%.*]]) {
; ALL-NEXT:    [[TMP1:%.*]] = call i32 @callee_different_types(ptr [[P]])
; ALL-NEXT:    ret void
;
  call i32 @callee_different_types(ptr %p)
  ret void
}

; The two loads overlap: Don't promote.
define internal i32 @callee_overlap(ptr %p) {
; ALL-LABEL: define {{[^@]+}}@callee_overlap
; ALL-SAME: (ptr [[P:%.*]]) {
; ALL-NEXT:    [[X:%.*]] = load i32, ptr [[P]], align 4
; ALL-NEXT:    [[P1:%.*]] = getelementptr i8, ptr [[P]], i64 2
; ALL-NEXT:    [[Y:%.*]] = load i32, ptr [[P1]], align 4
; ALL-NEXT:    [[Z:%.*]] = add i32 [[X]], [[Y]]
; ALL-NEXT:    ret i32 [[Z]]
;
  %x = load i32, ptr %p
  %p1 = getelementptr i8, ptr %p, i64 2
  %y = load i32, ptr %p1
  %z = add i32 %x, %y
  ret i32 %z
}

define void @caller_overlap(ptr %p) {
; ALL-LABEL: define {{[^@]+}}@caller_overlap
; ALL-SAME: (ptr [[P:%.*]]) {
; ALL-NEXT:    [[TMP1:%.*]] = call i32 @callee_overlap(ptr [[P]])
; ALL-NEXT:    ret void
;
  call i32 @callee_overlap(ptr %p)
  ret void
}

; Don't promote calls with function type mismatch.
define void @caller_type_mismatch() {
; CHECK-LABEL: define {{[^@]+}}@caller_type_mismatch() {
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @callee_type_mismatch(ptr null)
; CHECK-NEXT:    ret void
;
; ALL-LABEL: define {{[^@]+}}@caller_type_mismatch() {
; ALL-NEXT:    [[TMP1:%.*]] = call i32 @callee_type_mismatch(ptr null)
; ALL-NEXT:    ret void
;
  call i32 @callee_type_mismatch(ptr null)
  ret void
}

define internal void @callee_type_mismatch(ptr %p) {
; CHECK-LABEL: define {{[^@]+}}@callee_type_mismatch
; CHECK-SAME: (ptr [[P:%.*]]) {
; CHECK-NEXT:    ret void
;
; ALL-LABEL: define {{[^@]+}}@callee_type_mismatch
; ALL-SAME: (ptr [[P:%.*]]) {
; ALL-NEXT:    ret void
;
  ret void
}
